'use strict';
const $=id=>document.getElementById(id),canvas=$('room'),ctx=canvas.getContext('2d');
const rooms=new Image(),hero=new Image();
rooms.src='room.png';hero.src='pink-hero.png';
let W=360,H=310,last=0,ready=false,state;
const questions=[
{id:'coffee',x:125,time:'22:00',label:'テーブルのコーヒー',title:'寝る前のコーヒー。いつものあなたなら？',desc:'今日は家でゆっくり。テーブルには一杯のコーヒー。',answers:[{label:'飲む',loss:20,action:'コーヒーをひと口。今夜はもう少し起きていたい。'},{label:'飲まない',loss:0,action:'今夜のコーヒーは、おあずけ。'}],tip:'寝る前のカフェインが気になるなら、飲む時間や飲み物を見直してみよう。'},
{id:'phone',x:535,time:'22:30',label:'ベッドのそば',title:'ベッドに入ってからも、スマホを見る？',desc:'スマホに通知が届いた。つい気になってしまう。',answers:[{label:'まだ見る',loss:25,action:'スクロールしているうちに、時間が過ぎていく…。'},{label:'ここで置く',loss:0,action:'スマホを置いた。続きは、明日の楽しみに。'}],tip:'スマホを置く場所を、ベッドの外に決めてみよう。「あと少し」の区切りになります。'},
{id:'tv',x:350,time:'23:00',label:'テレビの前',title:'明日は早起き。もう一話、見る？',desc:'次のエピソードが始まりそう。いつもの自分なら？',answers:[{label:'もう一話',loss:20,action:'次の一話へ。時計の針も、先へ進んでいく。'},{label:'明日にする',loss:0,action:'テレビを消した。物語の続きは、また明日。'}],tip:'自動再生をオフにして、見る前に終わる時間を決めてみよう。'},
{id:'light',x:615,time:'23:30',label:'寝る準備',title:'もう寝る時間。明るい照明はどうする？',desc:'部屋の明かりが、まだついたまま。',answers:[{label:'つけたまま',loss:15,action:'明るいまま、ベッドへ。'},{label:'暗くする',loss:0,action:'明かりを落とすと、部屋は静かな夜の色に。'}],tip:'寝室の明るさを、自分が落ち着いて眠れる環境に整えてみよう。'},
{id:'alarm',x:625,time:'07:00',label:'翌朝のアラーム',title:'朝のアラーム。予定の時刻に起きる？',desc:'最近の自分を思い浮かべて、選んでみよう。',answers:[{label:'つい寝過ごす',loss:20,action:'もう少しだけ…。今朝のスタートは、少し後ろへ。'},{label:'予定どおり起きる',loss:0,action:'おはよう。新しい一日のはじまり。'}],tip:'起きる時刻が大きく変わるなら、生活に合う無理のないリズムを考えてみよう。'}
];
function resize(){const r=canvas.getBoundingClientRect();H=Math.max(170,Math.round(r.height*W/r.width));canvas.width=W;canvas.height=H;ctx.imageSmoothingEnabled=false;}
new ResizeObserver(resize).observe(canvas);
function reset(){if($('overlay').open)$('overlay').close();state={mode:'enter',step:0,hp:100,answers:[],playerX:-35,targetX:questions[0].x,camera:0,timer:0,anim:0,pose:0,reminded:false,pendingReminder:false,paused:false,dim:false,morning:false,done:false,activeAction:null,minutes:1320};$('effect').textContent='';$('clock').textContent='22:00';$('phase').textContent='おかえり';$('scene-label').textContent='あなたの部屋';$('caption').textContent='おかえりなさい。今日は、どんな夜にする？';$('question-label').textContent='今夜の冒険';$('question').textContent='まずは、お部屋へ。';$('description').textContent='答えを選ぶと、主人公が動きます。';$('choices').innerHTML='<div class="waiting">お部屋に入っています…</div>';$('honesty').textContent='いい答えより、いつもの答えを。';hud();}
function hud(){$('hp').textContent=state.hp;$('hp-bar').style.width=state.hp+'%';$('hp-bar').style.background=state.hp<60?'#eb9a9f':'#b9dc98';$('steps').innerHTML=questions.map((_,i)=>`<i class="${i<state.answers.length?'done':i===state.step?'current':''}" aria-label="${i+1}問目${i<state.answers.length?'回答済み':''}"></i>`).join('');}
function showQuestion(){state.mode='question';state.pose=0;state.activeAction=null;const q=questions[state.step];$('question-label').textContent=`${state.step+1} / 5　いつものあなたなら？`;$('question').textContent=q.title;$('description').textContent=q.desc;$('scene-label').textContent=q.label;$('phase').textContent=q.id==='alarm'?'おはよう':'あなたの夜';const [hh,mm]=q.time.split(':').map(Number);state.minutes=q.id==='alarm'?420:Math.max(state.minutes,hh*60+mm);$('clock').textContent=clockText();$('caption').textContent=q.id==='alarm'?'朝が来た。最後は、起きるときの習慣。':'いつもの自分に近い方を、タップ。';$('choices').innerHTML=q.answers.map((a,i)=>`<button class="choice" data-answer="${i}">${a.label}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));hud();}
function clockText(){return String(Math.floor(state.minutes/60)%24).padStart(2,'0')+':'+String(state.minutes%60).padStart(2,'0');}
function answer(index){if(!ready||state.mode!=='question'||state.paused||![0,1].includes(index))throw Error('今は回答できません。');const q=questions[state.step],a=q.answers[index];const before=state.hp;state.hp=Math.max(0,state.hp-a.loss);state.answers.push({id:q.id,title:q.title,label:a.label,loss:a.loss,tip:q.tip});state.mode='act';state.timer=0;state.activeAction={id:q.id,index};state.pose=q.id==='coffee'&&index===0?2:0;if(index===0&&['phone','tv','alarm'].includes(q.id))state.minutes+=q.id==='tv'?45:30;state.pendingReminder=before>=60&&state.hp<60&&!state.reminded;if(q.id==='light')state.dim=index===1;$('caption').textContent=a.action;$('honesty').textContent='あなたの選択を、記録しました。';document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;b.classList.toggle('selected',Number(b.dataset.answer)===index);});$('effect').textContent=a.loss?'−'+a.loss+' HP':'HP キープ！';$('effect').style.color=a.loss?'#ffafb6':'#e3edb7';$('effect').classList.remove('pop');void $('effect').offsetWidth;$('effect').classList.add('pop');hud();return snapshot();}
function next(){state.step++;state.activeAction=null;state.pose=0;$('effect').textContent='';if(state.step>=questions.length){state.mode='finishwalk';state.targetX=560;state.timer=0;$('choices').innerHTML='<div class="waiting">今夜の冒険を振り返っています…</div>';$('caption').textContent='５つの選択がそろいました。柳沢教授のもとへ。';return;}state.targetX=questions[state.step].x;state.mode='walk';state.timer=0;if(questions[state.step].id==='alarm'){state.morning=true;state.dim=false;$('caption').textContent='おやすみなさい。そして、朝がやってきた。';$('clock').textContent='07:00';}else $('caption').textContent='次の場面へ、てくてく。';$('choices').innerHTML='<div class="waiting">次の場面へ…</div>';}
function reminder(){state.mode='reminder';state.reminded=true;state.pendingReminder=false;const lastAnswer=state.answers.at(-1);openDialog(`<div class="dialog-banner">柳沢教授から、ひとこと</div><img class="portrait" src="yanagisawa.jpg" alt="柳沢正史氏の写真"><div class="dialog-body"><h2 id="dialog-title">……まだ寝ないんですか？</h2><p>${lastAnswer.tip}</p><p>ここから、ひとつ変えてみましょう。</p><button id="continue">つづきを見る</button><small>写真：筑波大学 IIIS。台詞は創作で、ご本人の発言ではありません。</small></div>`);$('continue').onclick=()=>{$('overlay').close();state.paused=false;next();};}
function finish(){state.done=true;state.mode='result';const perfect=state.hp===100,lowest=state.answers.filter(a=>a.loss).sort((a,b)=>b.loss-a.loss)[0];$('phase').textContent='結果発表';$('caption').textContent=perfect?'すべての場面で、睡眠HPを守りました。':'今夜は、ひとつ変えるところから。';$('question').textContent='おつかれさまでした。';$('description').textContent='５つの睡眠習慣を振り返りました。';$('choices').innerHTML='<button class="choice" id="view-result">結果をもう一度見る</button><button class="choice" id="replay">もう一度あそぶ</button>';$('view-result').onclick=()=>showResult(perfect,lowest);$('replay').onclick=reset;showResult(perfect,lowest);}
function showResult(perfect,lowest){openDialog(`<div class="dialog-banner">${perfect?'パーフェクト！ 柳沢教授からのメッセージ':'柳沢教授と、今夜を振り返ろう'}</div><img class="portrait" src="yanagisawa.jpg" alt="柳沢正史氏の写真"><div class="dialog-body"><h2 id="dialog-title">${perfect?'すばらしい！<br>眠る準備ができましたね。':'今夜は、ひとつ変えるところから。'}</h2><div class="result-score">${state.hp}<span> / 100 睡眠HP</span></div><p>${perfect?'５つの場面で、睡眠を大切にする選択ができました。おやすみなさい。':'選んだ習慣を振り返って、できそうなことをひとつ見つけてみましょう。'}</p>${lowest?`<p class="result-tip">${lowest.tip}</p>`:''}<details><summary>あなたの回答を見る</summary><ol class="answers">${state.answers.map(a=>`<li>${a.title}<br><strong>${a.label}</strong>${a.loss?'　−'+a.loss+' HP':'　HPキープ'}</li>`).join('')}</ol></details><button id="again">もう一度あそぶ</button><button id="share">結果をコピー</button><p id="copy-note" class="share-note" aria-live="polite"></p><small>満点は、このゲームの習慣選択での満点です。医学的な睡眠診断ではありません。台詞は創作であり、柳沢氏ご本人の発言・監修ではありません。</small></div>`);$('again').onclick=reset;$('share').onclick=async()=>{const text=`おやすみクエスト：睡眠HP ${state.hp}/100。５つの睡眠習慣を振り返りました。ゲーム上のスコアで、医学的な診断ではありません。`;try{await navigator.clipboard.writeText(text);$('copy-note').textContent='コピーしました。'}catch{$('copy-note').textContent=text;}};}
function openDialog(html){state.paused=true;$('dialog-content').innerHTML=html;$('overlay').showModal();}
function update(dt){if(!ready||state.paused)return;state.anim+=dt;if(['enter','walk','finishwalk'].includes(state.mode)){const diff=state.targetX-state.playerX;state.playerX+=Math.sign(diff)*Math.min(Math.abs(diff),dt*145);state.pose=Math.floor(state.anim*7)%2;if(Math.abs(diff)<2){state.pose=0;if(state.mode==='finishwalk')finish();else showQuestion();}}else if(state.mode==='act'){state.timer+=dt;if(state.timer>1.95){if(state.pendingReminder)reminder();else next();}}state.camera+=(Math.max(0,Math.min(360,state.playerX-150))-state.camera)*Math.min(1,dt*5);}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#302946';ctx.fillRect(0,0,W,H);if(!ready)return;const roomH=422,top=H-roomH,floor=top+roomH*.875;ctx.imageSmoothingEnabled=false;ctx.drawImage(rooms,0,0,rooms.naturalWidth,rooms.naturalHeight*.88,-state.camera,top,720,roomH);if(state.dim){ctx.fillStyle='#11123680';ctx.fillRect(0,0,W,H);}if(state.morning){ctx.fillStyle='#ffe4ad24';ctx.fillRect(0,0,W,H);}const walking=['enter','walk','finishwalk'].includes(state.mode),face=state.targetX<state.playerX?-1:1;const px=state.playerX-state.camera;const cw=hero.naturalWidth/3,ch=hero.naturalHeight;ctx.save();ctx.translate(px,floor-94+(walking?Math.sin(state.anim*14)*1.4:0));if(face<0){ctx.translate(80,0);ctx.scale(-1,1);}ctx.drawImage(hero,state.pose*cw,0,cw,ch,0,0,80,104);ctx.restore();if(state.activeAction?.id==='phone'&&state.activeAction.index===0){ctx.fillStyle='#b9c5ff';ctx.fillRect(px+52,floor-46,9,16);ctx.fillStyle='#afbfff25';ctx.fillRect(px+16,floor-70,55,62);}if(state.activeAction?.id==='tv'&&state.activeAction.index===0){ctx.fillStyle=`rgba(166,193,246,${.12+Math.sin(state.anim*8)*.08})`;ctx.fillRect(px-30,floor-100,90,75);}if(state.activeAction?.id==='coffee'&&state.activeAction.index===0){ctx.fillStyle='#ffe3c9';ctx.fillRect(px+52,floor-44,7,6);}if(state.mode==='act'&&state.timer>.4&&state.answers.at(-1)?.loss>0&&['phone','tv'].includes(state.activeAction?.id)){$('clock').textContent=clockText();}}
function loop(t){const dt=Math.min((t-last)/1000||0,.04);last=t;update(dt);draw();requestAnimationFrame(loop);}
function snapshot(){return {mode:state.mode,step:state.step,hp:state.hp,answers:state.answers,reminded:state.reminded,paused:state.paused,done:state.done,ready};}
$('restart').onclick=reset;$('info').onclick=()=>{openDialog('<div class="dialog-body"><h2 id="dialog-title">あそびかた</h2><p>主人公が部屋の中を歩きます。各場面で、いつもの自分に近い答えをタップしてください。</p><p>睡眠HPが60未満になると、柳沢教授の写真とともにヒントが登場。５問すべてでHPを守ると、満点のメッセージが見られます。</p><p>操作の上手さで点数は変わりません。起床や睡眠に困っていること自体を責めるためのゲームではありません。</p><button id="close-info">ゲームに戻る</button><small>本作は非公式コンセプト。数値はゲーム上の演出で、医学的な評価ではありません。<br><a href="https://airweave.jp/labo/sleep_diagnosis/light.shtml" target="_blank" rel="noopener">着想元：エアウィーヴ睡眠診断</a><br><a href="https://wpi-iiis.tsukuba.ac.jp/japanese/research/member/detail/masashiyanagisawa/" target="_blank" rel="noopener">写真出典：筑波大学 IIIS・柳沢正史氏</a>。台詞は創作で、ご本人・所属機関の監修や推薦ではありません。</small></div>');$('close-info').onclick=()=>{$('overlay').close();state.paused=false;};};$('overlay').addEventListener('cancel',e=>{e.preventDefault();$('overlay').close();state.paused=false;if(state.mode==='reminder')next();});
function assetsReady(){if(rooms.complete&&rooms.naturalWidth&&hero.complete&&hero.naturalWidth){ready=true;$('loading').style.display='none';}}for(const im of [rooms,hero]){im.onload=assetsReady;im.onerror=()=>{$('loading').textContent='読み込めませんでした。再読み込みしてください。';};}resize();reset();assetsReady();requestAnimationFrame(loop);
if(document.modelContext?.registerTool){const definitions=[{name:'read_sleep_game',description:'Read the room-question game state',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:snapshot},{name:'answer_sleep_question',description:'Answer the current sleep question with option 0 or 1. Wait until mode question.',inputSchema:{type:'object',properties:{option:{type:'integer',enum:[0,1]}},required:['option'],additionalProperties:false},execute:({option})=>answer(option)},{name:'restart_sleep_game',description:'Reset all answers and restart room entry',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{reset();return snapshot();}},{name:'continue_sleep_reminder',description:'Dismiss the professor reminder and continue to next question',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(state.mode!=='reminder')throw Error('No reminder');$('overlay').close();state.paused=false;next();return snapshot();}}];for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
